# -*- coding: utf-8 -*-
"""main.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1prEIRJfh6BAJGrfQbKmdrEmokjTlCHG3
"""



import joblib
import pandas as pd
from fastapi import FastAPI
from pydantic import BaseModel

model = joblib.load('model.pkl')
# Define the request data model
class StudentData(BaseModel):
    # Add all required fields from your dataset (except G3)
    school: str
    sex: str
    age: int
    address: str
    famsize: str
    Pstatus: str
    Medu: int
    Fedu: int
    Mjob: str
    Fjob: str
    reason: str
    guardian: str
    traveltime: int
    studytime: int
    failures: int
    schoolsup: str
    famsup: str
    paid: str
    activities: str
    nursery: str
    higher: str
    internet: str
    romantic: str
    famrel: int
    freetime: int
    goout: int
    Dalc: int
    Walc: int
    health: int
    absences: int
    G1: int
    G2: int
    course: str  # 'math' or 'portuguese'

# Create app
app = FastAPI()

@app.get("/")
def read_root():
    return {"message": "Student Grade Predictor API is running!"}

@app.post("/predict/")
def predict_grade(student: StudentData):
    # Convert input to DataFrame
    data = pd.DataFrame([student.dict()])

    # Predict using loaded model
    prediction = model.predict(data)[0]

    return {"predicted_grade": round(prediction, 2)}